apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacymedicinesupply-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PharmacyMedicineSupply
  template:
    metadata:
      labels:
        app: PharmacyMedicineSupply
    spec:
      containers:
      - name: pharmacymedicinesupplyrepos
        image: medicinesupplycr.azurecr.io/pharmacymedicinesupplyrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: pmsmsecret

---
apiVersion: v1
kind: Service
metadata:
  name: pharmacymedicinesupply
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PharmacyMedicineSupply
